import os
import re
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()  # reads your .env file so GROQ_API_KEY is available

client = Groq(api_key=os.getenv("GROQ_API_KEY"))


def groq_signal(text):
    """
    Signal 1: ask a Groq LLM to judge whether text reads as human or AI-generated.
    Returns a float from 0.0 (clearly human) to 1.0 (clearly AI).
    """
    prompt = f"""You are an AI-content detector. Assess whether the text below was
written by a human or generated by an AI language model.

Respond with ONLY a JSON object, no other text, in exactly this format:
{{"ai_score": <number between 0 and 1>, "reasoning": "<one short sentence>"}}

Where ai_score is:
- near 1.0 if the text strongly reads as AI-generated
- near 0.0 if it strongly reads as human-written
- near 0.5 if you genuinely cannot tell

Text to assess:
\"\"\"{text}\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.0,
    )

    raw = response.choices[0].message.content.strip()
    parsed = json.loads(raw)
    return float(parsed["ai_score"])


def stylometric_signal(text):
    """
    Signal 2: structural analysis of the text.
    Returns a float from 0.0 (reads human) to 1.0 (reads AI).
    Based on two metrics: sentence-length variance and type-token ratio.
    """
    # --- Split into sentences ---
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]

    # --- Split into words ---
    words = re.findall(r"\b\w+\b", text.lower())

    # Guard against tiny inputs that can't be measured meaningfully
    if len(sentences) < 2 or len(words) < 10:
        return 0.5  # not enough data — return pure uncertainty

    # --- Metric 1: sentence-length variance ---
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)

    # Convert variance to an "AI-ness" score: LOW variance -> high AI score.
    # We treat a variance of ~25 (std dev of 5 words) as clearly human.
    variance_ai_score = max(0.0, 1.0 - (variance / 25.0))

    # --- Metric 2: type-token ratio (vocabulary diversity) ---
    unique_words = len(set(words))
    ttr = unique_words / len(words)

    # Convert TTR to an "AI-ness" score: moderate/low diversity -> higher AI score.
    # TTR of ~0.7+ reads human; ~0.4 or below reads more uniform/AI.
    ttr_ai_score = max(0.0, min(1.0, (0.7 - ttr) / 0.3))

    # --- Combine the two metrics (variance weighted more, it's the stronger signal) ---
    stylo_score = 0.65 * variance_ai_score + 0.35 * ttr_ai_score
    return round(stylo_score, 3)


def combine_scores(llm_score, stylo_score):
    """
    Combine the two signal scores into a single confidence score (0-1).
    - Weighted average, LLM-heavy (Groq is the primary detector).
    - If the signals disagree strongly (>0.4 apart), pull toward 0.5
      to protect against false positives.
    Returns (confidence, attribution).
    """
    LLM_WEIGHT = 0.7
    STYLO_WEIGHT = 0.3

    # Weighted average
    combined = LLM_WEIGHT * llm_score + STYLO_WEIGHT * stylo_score

    # Disagreement check
    disagreement = abs(llm_score - stylo_score)
    if disagreement > 0.4:
        # Pull halfway toward 0.5 — strong disagreement means lower confidence
        combined = combined + (0.5 - combined) * 0.5

    combined = round(combined, 3)

    # Map to attribution using planning thresholds
    if combined >= 0.65:
        attribution = "likely_ai"
    elif combined >= 0.45:
        attribution = "uncertain"
    else:
        attribution = "likely_human"

    return combined, attribution

def generate_label(attribution):
    """
    Map an attribution category to its transparency label text.
    """
    labels = {
        "likely_ai": (
            "This content shows strong signals of AI generation. Our system "
            "assessed it with high confidence, but detection is not perfect — "
            "you are welcome to appeal with factual evidence."
        ),
        "likely_human": (
            "This content reads as human-written. Our system found no strong "
            "signals of AI generation."
        ),
        "uncertain": (
            "Our system could not determine with confidence whether this was "
            "written by a human or AI. Treat this result as inconclusive."
        ),
    }
    return labels[attribution]